apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flo-staging

resources:
  - ../../base

images:
  - name: 263797146828.dkr.ecr.eu-central-1.amazonaws.com/flo-cicd-lab
    newTag: "293c145966ec1a760265ac396e1f4bf06fa2c62b"

replicas:
  - name: flo-lab
    count: 2