apiVersion: apps/v1
kind: Deployment
metadata:
  name: flo-lab

spec:
  replicas: 1

  selector:
    matchLabels:
      app: flo-lab

  template:
    metadata:
      labels:
        app: flo-lab

    spec:
      containers:
        - name: flo-lab
          image: 263797146828.dkr.ecr.eu-central-1.amazonaws.com/flo-cicd-lab:v1

          ports:
            - containerPort: 8080

          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10