apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flo-production

resources:
  - ../../base

images:
  - name: 263797146828.dkr.ecr.eu-central-1.amazonaws.com/flo-cicd-lab
    newTag: v1